In [1]:
# [과제] 인덱싱을 이용하여 특정 컬럼, 특정 행, 특정 값을 추출
import pandas as pd
file_data = pd.read_csv('./dataset/file_data.csv')
file_data['가격'] = [5000,5000,4000,5000,3000]
file_data

FileNotFoundError: [Errno 2] No such file or directory: './dataset/file_data.csv'

In [ ]:
# [과제] 행, 열 모두에 조건 지정

In [3]:
import numpy as np
import pandas as pd
columns = ['kor','eng','art','math','gym','sci']
index = ['jim','sam','tom','tim','bob']
data = np.random.randint(70,100,size=(5,6))
df = pd.DataFrame(data,index,columns=columns)
df

     kor  eng  art  math  gym  sci
jim   91   78   84    72   95   79
sam   87   94   73    95   80   77
tom   85   75   71    96   75   96
tim   90   90   93    97   84   98
bob   91   95   90    95   77   91

[과제] iloc, loc를 이용해서 아래 요구사항들을 출력하세요

- df의 kor열을 series와 dataframe을 각각 출력
- df에서 sam의 math 점수를 출력(2가지 방법)
- df에서 tom의 eng와 sci 점수를 출력(2가지 방법)
- df에서 jim, tim의 eng, gym 점수를 출력
- df에서 jim, sam의 art,math,gym 점수를 출력

[과제] iloc, loc를 이용해서 아래 요구사항들을 수행하세요

- df에서 sam의 math 점수를 100으로 변경
- df에서 tom의 eng와 math 점수를 100으로 변경
- df에서 jim, tim의 kor, gym 점수를 null값으로 변경
- df에서 math와 gym 점수를 바꾸어 출력

In [5]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# [과제] 데이터 추출(인덱싱, 조건), 변경, 삭제, 정렬, 칼럼 병합(sibsp + parch = family) 등을 수행하여 데이터에서 인사이트를 찾아보세